// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/repository.go

// Package mock_repository is a generated GoMock package.
package mock_repository

import (
	context "context"
	sql "database/sql"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockTransaction is a mock of Transaction interface.
type MockTransaction struct {
	ctrl     *gomock.Controller
	recorder *MockTransactionMockRecorder
}

// MockTransactionMockRecorder is the mock recorder for MockTransaction.
type MockTransactionMockRecorder struct {
	mock *MockTransaction
}

// NewMockTransaction creates a new mock instance.
func NewMockTransaction(ctrl *gomock.Controller) *MockTransaction {
	mock := &MockTransaction{ctrl: ctrl}
	mock.recorder = &MockTransactionMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTransaction) EXPECT() *MockTransactionMockRecorder {
	return m.recorder
}

// Transaction mocks base method.
func (m *MockTransaction) Transaction(arg0 context.Context, arg1 func(context.Context) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Transaction", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Transaction indicates an expected call of Transaction.
func (mr *MockTransactionMockRecorder) Transaction(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Transaction", reflect.TypeOf((*MockTransaction)(nil).Transaction), arg0, arg1)
}

// MockTransactionWithOptions is a mock of TransactionWithOptions interface.
type MockTransactionWithOptions struct {
	ctrl     *gomock.Controller
	recorder *MockTransactionWithOptionsMockRecorder
}

// MockTransactionWithOptionsMockRecorder is the mock recorder for MockTransactionWithOptions.
type MockTransactionWithOptionsMockRecorder struct {
	mock *MockTransactionWithOptions
}

// NewMockTransactionWithOptions creates a new mock instance.
func NewMockTransactionWithOptions(ctrl *gomock.Controller) *MockTransactionWithOptions {
	mock := &MockTransactionWithOptions{ctrl: ctrl}
	mock.recorder = &MockTransactionWithOptionsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTransactionWithOptions) EXPECT() *MockTransactionWithOptionsMockRecorder {
	return m.recorder
}

// TransactionWithOptions mocks base method.
func (m *MockTransactionWithOptions) TransactionWithOptions(arg0 context.Context, arg1 *sql.TxOptions, arg2 func(context.Context) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TransactionWithOptions", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// TransactionWithOptions indicates an expected call of TransactionWithOptions.
func (mr *MockTransactionWithOptionsMockRecorder) TransactionWithOptions(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TransactionWithOptions", reflect.TypeOf((*MockTransactionWithOptions)(nil).TransactionWithOptions), arg0, arg1, arg2)
}
