// Code generated by pi-cli. DO NOT EDIT.
// versions:
// 	pi-cli v0.3.2
// 	pi v0.3.2
// 	source: user.proto

package user

import (
	"context"
	"fmt"
	"reflect"
)

// Request Wrappers
type GetProfileRequestWrapper struct {
	ctx context.Context
	*GetProfileRequest
}

func (h *GetProfileRequestWrapper) Context() context.Context {
	return h.ctx
}

func (h *GetProfileRequestWrapper) Param(s string) string {
	return ""
}

func (h *GetProfileRequestWrapper) PathParam(s string) string {
	return ""
}

func (h *GetProfileRequestWrapper) Bind(p interface{}) error {
	ptr := reflect.ValueOf(p)
	if ptr.Kind() != reflect.Ptr {
		return fmt.Errorf("expected a pointer, got %T", p)
	}

	hValue := reflect.ValueOf(h.GetProfileRequest).Elem()
	ptrValue := ptr.Elem()

	for i := 0; i < hValue.NumField(); i++ {
		field := hValue.Type().Field(i)
		if field.Name == "state" || field.Name == "sizeCache" || field.Name == "unknownFields" {
			continue
		}

		if field.IsExported() {
			ptrValue.Field(i).Set(hValue.Field(i))
		}
	}

	return nil
}

func (h *GetProfileRequestWrapper) HostName() string {
	return ""
}

func (h *GetProfileRequestWrapper) Params(s string) []string {
	return nil
}

type LoginRequestWrapper struct {
	ctx context.Context
	*LoginRequest
}

func (h *LoginRequestWrapper) Context() context.Context {
	return h.ctx
}

func (h *LoginRequestWrapper) Param(s string) string {
	return ""
}

func (h *LoginRequestWrapper) PathParam(s string) string {
	return ""
}

func (h *LoginRequestWrapper) Bind(p interface{}) error {
	ptr := reflect.ValueOf(p)
	if ptr.Kind() != reflect.Ptr {
		return fmt.Errorf("expected a pointer, got %T", p)
	}

	hValue := reflect.ValueOf(h.LoginRequest).Elem()
	ptrValue := ptr.Elem()

	for i := 0; i < hValue.NumField(); i++ {
		field := hValue.Type().Field(i)
		if field.Name == "state" || field.Name == "sizeCache" || field.Name == "unknownFields" {
			continue
		}

		if field.IsExported() {
			ptrValue.Field(i).Set(hValue.Field(i))
		}
	}

	return nil
}

func (h *LoginRequestWrapper) HostName() string {
	return ""
}

func (h *LoginRequestWrapper) Params(s string) []string {
	return nil
}

type RegisterRequestWrapper struct {
	ctx context.Context
	*RegisterRequest
}

func (h *RegisterRequestWrapper) Context() context.Context {
	return h.ctx
}

func (h *RegisterRequestWrapper) Param(s string) string {
	return ""
}

func (h *RegisterRequestWrapper) PathParam(s string) string {
	return ""
}

func (h *RegisterRequestWrapper) Bind(p interface{}) error {
	ptr := reflect.ValueOf(p)
	if ptr.Kind() != reflect.Ptr {
		return fmt.Errorf("expected a pointer, got %T", p)
	}

	hValue := reflect.ValueOf(h.RegisterRequest).Elem()
	ptrValue := ptr.Elem()

	for i := 0; i < hValue.NumField(); i++ {
		field := hValue.Type().Field(i)
		if field.Name == "state" || field.Name == "sizeCache" || field.Name == "unknownFields" {
			continue
		}

		if field.IsExported() {
			ptrValue.Field(i).Set(hValue.Field(i))
		}
	}

	return nil
}

func (h *RegisterRequestWrapper) HostName() string {
	return ""
}

func (h *RegisterRequestWrapper) Params(s string) []string {
	return nil
}

type UpdateProfileRequestWrapper struct {
	ctx context.Context
	*UpdateProfileRequest
}

func (h *UpdateProfileRequestWrapper) Context() context.Context {
	return h.ctx
}

func (h *UpdateProfileRequestWrapper) Param(s string) string {
	return ""
}

func (h *UpdateProfileRequestWrapper) PathParam(s string) string {
	return ""
}

func (h *UpdateProfileRequestWrapper) Bind(p interface{}) error {
	ptr := reflect.ValueOf(p)
	if ptr.Kind() != reflect.Ptr {
		return fmt.Errorf("expected a pointer, got %T", p)
	}

	hValue := reflect.ValueOf(h.UpdateProfileRequest).Elem()
	ptrValue := ptr.Elem()

	for i := 0; i < hValue.NumField(); i++ {
		field := hValue.Type().Field(i)
		if field.Name == "state" || field.Name == "sizeCache" || field.Name == "unknownFields" {
			continue
		}

		if field.IsExported() {
			ptrValue.Field(i).Set(hValue.Field(i))
		}
	}

	return nil
}

func (h *UpdateProfileRequestWrapper) HostName() string {
	return ""
}

func (h *UpdateProfileRequestWrapper) Params(s string) []string {
	return nil
}
