// Code generated by pi-cli. DO NOT EDIT.
// versions:
// 	pi-cli v0.4.1
// 	pi v0.4.1
// 	source: user.proto

package user

import (
	"context"
	piGRPC "github.com/sllt/pi/pkg/pi/grpc"
)

// Request Wrappers
type GetProfileRequestWrapper struct {
	ctx context.Context
	*GetProfileRequest
}

func (h *GetProfileRequestWrapper) Context() context.Context {
	return h.ctx
}

func (h *GetProfileRequestWrapper) Param(s string) string {
	return ""
}

func (h *GetProfileRequestWrapper) PathParam(s string) string {
	return ""
}

func (h *GetProfileRequestWrapper) Bind(p interface{}) error {
	return piGRPC.BindRequest(p, h.GetProfileRequest)
}

func (h *GetProfileRequestWrapper) HostName() string {
	return ""
}

func (h *GetProfileRequestWrapper) Params(s string) []string {
	return nil
}

type LoginRequestWrapper struct {
	ctx context.Context
	*LoginRequest
}

func (h *LoginRequestWrapper) Context() context.Context {
	return h.ctx
}

func (h *LoginRequestWrapper) Param(s string) string {
	return ""
}

func (h *LoginRequestWrapper) PathParam(s string) string {
	return ""
}

func (h *LoginRequestWrapper) Bind(p interface{}) error {
	return piGRPC.BindRequest(p, h.LoginRequest)
}

func (h *LoginRequestWrapper) HostName() string {
	return ""
}

func (h *LoginRequestWrapper) Params(s string) []string {
	return nil
}

type RegisterRequestWrapper struct {
	ctx context.Context
	*RegisterRequest
}

func (h *RegisterRequestWrapper) Context() context.Context {
	return h.ctx
}

func (h *RegisterRequestWrapper) Param(s string) string {
	return ""
}

func (h *RegisterRequestWrapper) PathParam(s string) string {
	return ""
}

func (h *RegisterRequestWrapper) Bind(p interface{}) error {
	return piGRPC.BindRequest(p, h.RegisterRequest)
}

func (h *RegisterRequestWrapper) HostName() string {
	return ""
}

func (h *RegisterRequestWrapper) Params(s string) []string {
	return nil
}

type UpdateProfileRequestWrapper struct {
	ctx context.Context
	*UpdateProfileRequest
}

func (h *UpdateProfileRequestWrapper) Context() context.Context {
	return h.ctx
}

func (h *UpdateProfileRequestWrapper) Param(s string) string {
	return ""
}

func (h *UpdateProfileRequestWrapper) PathParam(s string) string {
	return ""
}

func (h *UpdateProfileRequestWrapper) Bind(p interface{}) error {
	return piGRPC.BindRequest(p, h.UpdateProfileRequest)
}

func (h *UpdateProfileRequestWrapper) HostName() string {
	return ""
}

func (h *UpdateProfileRequestWrapper) Params(s string) []string {
	return nil
}
