// Code generated by pi-cli. DO NOT EDIT.
// versions:
// 	pi-cli v0.4.1
// 	pi v0.4.1
// 	source: user.proto

package user

import (
	"context"

	"github.com/sllt/pi/pkg/pi"
	piGRPC "github.com/sllt/pi/pkg/pi/grpc"
	"github.com/sllt/pi/pkg/pi/infra"
	"google.golang.org/grpc"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/status"

	healthpb "google.golang.org/grpc/health/grpc_health_v1"
)

// NewUserServicePiServer creates a new instance of UserServicePiServer
func NewUserServicePiServer() *UserServicePiServer {
	return &UserServicePiServer{
		health: getOrCreateHealthServer(), // Initialize the health server
	}
}

// UserServiceServerWithPi is the interface for the server implementation
type UserServiceServerWithPi interface {
	Register(*pi.Context) (any, error)
	Login(*pi.Context) (any, error)
	GetProfile(*pi.Context) (any, error)
	UpdateProfile(*pi.Context) (any, error)
}

// UserServiceServerWrapper wraps the server and handles request and response logic
type UserServiceServerWrapper struct {
	UserServiceServer
	*healthServer
	Container *infra.Container
	app       *pi.App
	server    UserServiceServerWithPi
}

// Unary method handler for Register
func (h *UserServiceServerWrapper) Register(ctx context.Context, req *RegisterRequest) (*RegisterResponse, error) {
	gctx := h.getPiContext(ctx, &RegisterRequestWrapper{ctx: ctx, RegisterRequest: req})

	res, err := h.server.Register(gctx)
	if err != nil {
		return nil, piGRPC.MapError(err)
	}

	resp, ok := res.(*RegisterResponse)
	if !ok {
		return nil, status.Error(codes.Internal, "internal server error")
	}

	return resp, nil
}

// Unary method handler for Login
func (h *UserServiceServerWrapper) Login(ctx context.Context, req *LoginRequest) (*LoginResponse, error) {
	gctx := h.getPiContext(ctx, &LoginRequestWrapper{ctx: ctx, LoginRequest: req})

	res, err := h.server.Login(gctx)
	if err != nil {
		return nil, piGRPC.MapError(err)
	}

	resp, ok := res.(*LoginResponse)
	if !ok {
		return nil, status.Error(codes.Internal, "internal server error")
	}

	return resp, nil
}

// Unary method handler for GetProfile
func (h *UserServiceServerWrapper) GetProfile(ctx context.Context, req *GetProfileRequest) (*GetProfileResponse, error) {
	gctx := h.getPiContext(ctx, &GetProfileRequestWrapper{ctx: ctx, GetProfileRequest: req})

	res, err := h.server.GetProfile(gctx)
	if err != nil {
		return nil, piGRPC.MapError(err)
	}

	resp, ok := res.(*GetProfileResponse)
	if !ok {
		return nil, status.Error(codes.Internal, "internal server error")
	}

	return resp, nil
}

// Unary method handler for UpdateProfile
func (h *UserServiceServerWrapper) UpdateProfile(ctx context.Context, req *UpdateProfileRequest) (*UpdateProfileResponse, error) {
	gctx := h.getPiContext(ctx, &UpdateProfileRequestWrapper{ctx: ctx, UpdateProfileRequest: req})

	res, err := h.server.UpdateProfile(gctx)
	if err != nil {
		return nil, piGRPC.MapError(err)
	}

	resp, ok := res.(*UpdateProfileResponse)
	if !ok {
		return nil, status.Error(codes.Internal, "internal server error")
	}

	return resp, nil
}

// mustEmbedUnimplementedUserServiceServer ensures implementation
func (h *UserServiceServerWrapper) mustEmbedUnimplementedUserServiceServer() {}

// RegisterUserServiceServerWithPi registers the server
func RegisterUserServiceServerWithPi(app *pi.App, srv UserServiceServerWithPi) {
	registerServerWithPi(app, srv, func(s grpc.ServiceRegistrar, srv any) {
		wrapper := &UserServiceServerWrapper{
			server:       srv.(UserServiceServerWithPi),
			healthServer: &healthServer{app.GRPCHealthServer()},
			app:          app,
		}

		RegisterUserServiceServer(s, wrapper)

		wrapper.healthServer.Server.SetServingStatus("user.UserService", healthpb.HealthCheckResponse_SERVING)
	})
}

// getPiContext creates Pi context
func (h *UserServiceServerWrapper) getPiContext(ctx context.Context, req pi.Request) *pi.Context {
	c := h.app.NewContext(ctx)
	c.Request = req
	return c
}
